### ISSUE TITLE
The File Organizer plugin is causing errors in the display of the Tasks plugin

### ISSUE THREAD

**Issue by kenanking** [different-ai/file-organizer-2000#174] opened 2024-07-31 15:14 UTC
Using the File Organizer plugin causes errors in the display of the date and time settings interface for the Tasks plugin.

![After enabling File Organizer](https://github.com/user-attachments/assets/5a757605-1ae0-484b-b3e6-eb7c6c2a956b)

![Before enabling File Organizer](https://github.com/user-attachments/assets/66911541-5aac-4b1a-9efb-6f18bbc9bae6)

**Comment by aexshafii** [comment] 2024-08-01 17:51
hey @kenanking Thanks for adding this issue. Can you point out where the issue is exactly? I'm not familiar with this plugin

**Comment by aexshafii** [comment] 2024-08-01 17:52
@kenanking thanks! Will have a look at this and keep you posted.

**Comment by aexshafii** [comment] 2024-08-01 17:57
@kenanking Should be fixed! Can you update to version 1.23.1 of the plugin and try again?

**Comment by kenanking** [comment] 2024-08-01 17:57
> @kenanking Should be fixed! Can you update to version 1.23.1 of the plugin and try again?

Hello, after updating to today's version (1.23.1), the issue mentioned above no longer occurs. The screenshot above was taken using version 1.23.0.

**Closed** 2024-08-02 01:24 UTC
